version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./heimdall:/config
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=thibsleswag.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=c3108850-8666-42b9-863a-fb1c2ea00aac
      - EMAIL=zarcor26@gmail.com
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis

  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - nitter:/data
      - ./nitter/nitter.conf:/src/nitter.conf

  mariadb1:
    image: mariadb:latest
    container_name: mariadb1
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nextcloud
    volumes:
      - mariadb1:/var/lib/mysql

  mariadb2:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
    volumes:
      - mariadb2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb1
      - mariadb2
    environment:
      PMA_ARBITRARY: 1
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    links:
      - mariadb1
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_HOST: mariadb1

  wordpress:
    image: wordpress
    restart: always
    links:
      - mariadb2
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb2
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  openldap:
    image: osixia/openldap:1.2.3
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #docker-compose.ymlLDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    domainname: "example.org" # important: same as hostname
    hostname: "example.org"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap

  plik:
    image: rootgg/plik:latest
    container_name: plik
    volumes:
      - ./plik/plikd.cfg:/home/plik/server/plikd.cfg
      - plik-files:/home/plik/server/files
    restart: "unless-stopped"
  
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    volumes:
      - portainer:/var/run/docker.sock
      - portainer:/data

  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001

  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb3:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=root
    restart: always
    volumes:
      - gitea:/data
      - gitea:/etc/timezone:ro
      - gitea:/etc/localtime:ro
    depends_on:
      - mariadb3

  mariadb3:
    image: mariadb:latest
    container_name: mariadb3
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gitea
    volumes:
      - mariadb3:/var/lib/mysql

  mattermost-postgres:
    container_name: mattermost-postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mattermost
      PGDATA: /mattermost/postgres
    volumes:
       - mattermost-postgres:/mattermost/postgres
    restart: unless-stopped

  mattermost-server:
    container_name: mattermost-server
    build:
      context: ./mattermost
    image: mattermost-server:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - mattermost-server:/opt/mattermost/data
    restart: unless-stopped
    depends_on:
      - mattermost-postgres
    ulimits:
      nofile: 49152

volumes:
  portainer:
  portainer-agent:
  plik:
  gitea:
  mattermost-server:
  mattermost-postgres:
  mariadb1:
  mariadb2:
  mariadb3:
  wordpress:
  nextcloud:
  nitter:
  redis:
  plik-files: